Added RecaptchaV2 task support
ScreamZ/anti-captcha pull request #19
Opened 2021-07-09 21:29 UTC by HugoLeblanc

2021-07-12 09:12 UTC, ScreamZ requested changes

2021-07-12 09:12 UTC, ScreamZ commented on package.json
> +  "name": "@hugoleblanc/anticaptcha",
Please don't change package name

2021-07-12 09:12 UTC, ScreamZ commented on package.json
> +    "url": "https://github.com/HugoLeblanc/anti-captcha.git"
Please don't change repository

2021-07-12 09:12 UTC, ScreamZ commented on package.json
> +    "url": "https://github.com/HugoLeblanc/anti-captcha.git"
Please don't change repository

2021-07-12 09:12 UTC, ScreamZ commented
Thanks for the pull request, a few changes and we are ready to merge :-)

2021-07-12 10:24 UTC, HugoLeblanc commented
Here we go, edited package.json.

2021-07-14 17:22 UTC, ScreamZ approved these changes

2021-07-14 17:22 UTC, merged

2021-07-14 17:25 UTC, ScreamZ commented
Released under `2.0.6` on npm ✌🏻